name: CI

on:
  push:
    branches:
      - master
      - dev
      
    paths-ignore:
      - '**.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run linter
        run: ./vendor/bin/duster lint

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist 

      - name: Run analyser
        run: ./vendor/bin/phpstan analyse

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [lint, static-analysis]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: sevenbooks
          MYSQL_ROOT_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      
      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run npm install
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run storage link
        run: php artisan storage:link

      - name: Clear view cache
        run: php artisan view:clear
      
      - name: Clear config cache
        run: php artisan config:clear

      - name: Clear app cache
        run: php artisan cache:clear

      - name: Generate key
        run: php artisan key:generate --env=testing

      - name: Run tests
        run: php artisan test
